### ISSUE TITLE
Variant 12_122064773_CCCGCCA_C_clinical 

### ISSUE THREAD

**Issue by genecracker** [Clinical-Genomics/MIP#1054] opened 2019-10-03 13:49 UTC
not present in local database but AF 99% in gnomAD? Rank score 15. Can you check this variant? Something seems off. 

Kind regards,
Bianca

**Comment by henrikstranneheim** [comment] 2019-10-07 15:00
@genecracker Could you post a link so that I can look at the actual case and variant?

**Comment by genecracker** [comment] 2019-10-10 13:50
https://scout.scilifelab.se/cust004/719701400132fam/f91d75d41b431ae3da3e4ff1696d81db

**Comment by genecracker** [comment] 2019-10-10 13:51
We see this variant also on other cases from Clinical Immunology

**Comment by dnil** [comment] 2019-10-10 14:33
Thanks! The main reason you see it at all is the big boost it got from being classified as "Conflicting interpretations of **pathogenic**ity" in clinvar (and GenMod has some issues with the new ClinVar annotation format). See https://github.com/Clinical-Genomics/scout/issues/1366. Also, for a few weeks gnomAD annotation was unnormalised; see https://github.com/Clinical-Genomics/scout/issues/1368. This has been resolved, but interim cases need a rerun if you want to take advantage of the fix..

We are working on a fix for scout that will allow loading all ClinVar variants, then de-value the ClinVar variants in the rank model again, and allow manual triage in scout on a need to do basis.

That said, it will be interesting to see what the VCFs looked like for this variant: by the looks of it, it actually gets a downvote on frequency, hinting that **something** was working and that there may yet be an issue with Scout/loqusdb loading/displaying local frequency as well?

**Comment by sofievonlanthen** [comment] 2019-10-10 14:34
I have the same variant in my case. I noticed when looking in Ensembl that GRCh37 has 7 Prolines (this variant is a DEL of 2 Prolines) but the GRCh38 version has only 5 Pro (6 bp or 2 aa less than the version in 37). So this is no longer a variant in 38 but actually matches the ref ?

**Comment by genecracker** [comment] 2019-10-16 08:49
Hi,

See even this variant: https://scout.scilifelab.se/cust004/219701400067fam/b398d31d45b103ccbc3e6aa1c0b14160

I understand it get ranked high because of clinvar "pathogenic" from 2004 (this case was uploaded just after the latest Scout update and before the fix)....but I am more surprise about the variant not being in local database?

**Comment by dnil** [comment] 2019-10-16 11:18
My best guess is that variants extremely common (>40%?) in the fixed population dbs are not normally logged in loqusdb? Correct @moonso @jemten?
If you hit a rerun on the case, it should disappear of course.

**Comment by jemten** [comment] 2019-10-16 11:21
@dnil You're right. 
We filter out variants that are that common (40% as you say), thus they will never make it to locusdb.

**Comment by dnil** [comment] 2019-10-16 11:27
Thank you @jemten - and @genecracker for reporting! As far as I understand, a deviation has been filed, and the issue is resolved. May I then suggest that you hit rerun for both cases, and we close this for now! Please reopen if you find them/similar ones again in a fresh case!

**Closed by dnil** 2019-10-16 11:27 UTC
